apiVersion: v2
name: scapi
description: A helm chart for scapi deployment
type: application
version: 0.3.89
appVersion: 0.3.89
maintainers:
    - name: Rob Barnsley
      email: rob.barnsley@skao.int
